#!/bin/bash
set -e

# generate the build directory
npm run --silent build

files=$(git ls-files scss | sed -e 's#^scss/##' | sed -e 's#/.*$##' | sort -u)
echo $files > publish-files.log
cd scss
cp -rv $files ..
cd -
